# Generated by Django 4.2.2 on 2023-07-01 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_remove_question_course_question_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='date_enrolled',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
