# Generated by Django 4.2.2 on 2023-07-01 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0005_rename_date_enrolled_submission_date_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date_submitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
